# Diesel Truck Regional Distribution Configuration

# Basic vehicle information
vehicle_info:
  type: "diesel"
  category: "articulated"  # Regional distribution typically uses articulated trucks
  name: "Regional Diesel Distribution"
  description: "Conventional diesel articulated truck for regional distribution operations"

# Purchase and cost information
purchase:
  base_price_2025: 220000  # AUD
  annual_price_decrease_real: 0.0  # 0% real decrease per year
  notes: "Diesel truck prices stable or increasing slightly with emission standards"

# Engine specifications
engine:
  power_kw: 450  # Higher power for regional operations
  displacement_litres: 13.0
  emission_standard: "Euro VI"
  adblue_consumption_percent: 0.05  # 5% of diesel consumption
  engine_oil_capacity_litres: 45

# Fuel consumption
fuel_consumption:
  # Base consumption rates in L/100km
  base_rate_l_per_100km: 38.0  # Regional diesel consumption
  consumption_range:
    min: 35.0
    max: 45.0
  
  # Adjustment factors
  load_adjustment_factor: 0.25  # 25% increase at full load vs empty
  temperature_adjustment:
    hot_weather: 0.03  # 3% increase in hot weather
    cold_weather: 0.05  # 5% increase in cold weather
  
  # Idling
  idle_consumption_l_per_hour: 3.0
  estimated_idle_hours_per_1000km: 5.0  # Lower idle time compared to urban but higher than long-haul

# Refueling specifications
refueling:
  tank_capacity_litres: 800
  refueling_time_minutes: 20
  
  # Refueling strategies
  refueling_strategy: "depot"  # Default strategy
  strategies:
    depot:
      description: "Refuel at depot"
      frequency_days: 3
    public:
      description: "Refuel at public stations"
      frequency_days: 2
      price_premium_percent: 0.02  # 2% higher price at public stations

# Performance specifications
performance:
  max_payload_tonnes: 28  # Higher than BET due to lighter engine
  range_km: 2000  # Higher range with diesel
  max_speed_kph: 100
  acceleration_0_50_kph_seconds: 20
  gradeability_percent: 12

# Maintenance
maintenance:
  cost_per_km: 0.16  # AUD per km, higher than BET
  annual_cost_at_reference_km: 12800  # At 80,000 km annually
  reference_km: 80000  # Higher annual distance for regional operations
  scheduled_maintenance_interval_km: 25000  # More frequent than BET
  major_service_interval_km: 100000
  
  # Detailed costs
  detailed_costs:
    annual_fixed_min: 2000
    annual_fixed_max: 4000
    per_km_variable: 0.12
    notes: "Higher maintenance due to engine complexity, more frequent service intervals"

# Emissions
emissions:
  co2_g_per_km: 1020  # Based on fuel consumption
  nox_g_per_km: 0.35
  pm_g_per_km: 0.01
  ghg_g_co2e_per_km: 1050  # Including non-CO2 GHGs
  
  # Carbon cost
  carbon_cost_per_tonne_co2e: 50  # AUD per tonne CO2e
  carbon_cost_included: false  # Default setting

# Available models reference
available_models:
  - manufacturer: "Volvo"
    model: "FH 500"
    power_kw: 500
    displacement_litres: 13.0
    emission_standard: "Euro VI"
  - manufacturer: "Mercedes-Benz"
    model: "Actros 2646"
    power_kw: 460
    displacement_litres: 12.8
    emission_standard: "Euro VI"
  - manufacturer: "Scania"
    model: "R 500"
    power_kw: 500
    displacement_litres: 13.0
    emission_standard: "Euro VI" 