# Battery Electric Truck (BET) Default Configuration

# Basic vehicle information
vehicle_info:
  type: "battery_electric"
  category: "articulated"  # Options: "rigid", "articulated"
  name: "Default BET Articulated"
  description: "Standard battery electric articulated truck (prime mover)"

# Purchase and cost information
purchase:
  base_price_2025: 400000  # AUD
  annual_price_decrease_real: 0.02  # 2% real decrease per year
  notes: "Expected to reach ~300,000 by 2030"

# Battery specifications
battery:
  capacity_kwh: 500
  usable_capacity_percentage: 0.90  # 90% of total capacity is usable
  degradation_rate_annual: 0.02  # 2% capacity loss per year
  replacement_threshold: 0.70  # Replace at 70% of original capacity
  expected_lifecycle_years: 8  # Expected years before replacement
  replacement_cost_factor: 0.80  # Replacement cost as percentage of new battery

# Energy consumption
energy_consumption:
  # Base consumption rates in kWh/km
  base_rate_kwh_per_km: 1.45
  consumption_range:
    min: 1.40
    max: 1.50
  
  # Adjustment factors
  load_adjustment_factor: 0.15  # 15% increase at full load vs empty
  temperature_adjustment:
    hot_weather: 0.05  # 5% increase in hot weather
    cold_weather: 0.15  # 15% increase in cold weather
  
  # Regenerative braking
  regenerative_braking_efficiency: 0.65  # 65% energy recovery efficiency
  regen_contribution_urban: 0.20  # 20% energy saving in urban driving

# Charging specifications
charging:
  max_charging_power_kw: 350
  charging_efficiency: 0.90  # 90% of electricity from grid becomes battery energy
  
  # Charging strategies and times
  charging_strategy: "overnight_depot"  # Default strategy
  strategies:
    overnight_depot:
      description: "Full charge overnight at depot"
      time_required_hours: 8
      electricity_rate_type: "off_peak_tou"
    opportunity:
      description: "Fast charging during operation"
      time_required_hours: 1
      electricity_rate_type: "average_flat_rate"

# Performance specifications
performance:
  max_payload_tonnes: 26
  range_km: 350
  max_speed_kph: 90
  acceleration_0_50_kph_seconds: 20
  gradeability_percent: 12

# Maintenance
maintenance:
  cost_per_km: 0.08  # AUD per km
  annual_cost_at_reference_km: 6400  # At 80,000 km annually
  reference_km: 80000
  scheduled_maintenance_interval_km: 40000
  major_service_interval_km: 120000
  
  # Detailed costs
  detailed_costs:
    annual_fixed_min: 700
    annual_fixed_max: 1500
    per_km_variable: 0.05
    notes: "Higher complexity/scale than rigid trucks"

# Available models reference
available_models:
  - manufacturer: "Volvo"
    model: "FH Electric"
    battery_kwh: [340, 510]
    range_km: [200, 300]
    max_charging_kw: 250
  - manufacturer: "Mercedes-Benz"
    model: "eActros 600"
    battery_kwh: 600
    range_km: 500
    max_charging_kw: 1000
    notes: "MCS charger capability"
  - manufacturer: "Scania"
    model: "25 P/R/S EV"
    battery_kwh: 728
    range_km: [250, 375]
    max_charging_kw: 375