# Battery Electric Truck (BET) Regional Distribution Configuration

# Basic vehicle information
vehicle_info:
  type: "battery_electric"
  category: "articulated"  # Regional distribution typically uses articulated trucks
  name: "Regional BET Distribution"
  description: "Battery electric articulated truck for regional distribution operations"

# Purchase and cost information
purchase:
  base_price_2025: 450000  # AUD
  annual_price_decrease_real: 0.02  # 2% real decrease per year
  notes: "Higher battery capacity needed for regional operations increases cost"

# Battery specifications
battery:
  capacity_kwh: 600  # Higher capacity needed for regional routes
  usable_capacity_percentage: 0.90  # 90% of total capacity is usable
  degradation_rate_annual: 0.02  # 2% capacity loss per year
  replacement_threshold: 0.70  # Replace at 70% of original capacity
  expected_lifecycle_years: 7  # Expected years before replacement
  replacement_cost_factor: 0.75  # Replacement cost as percentage of new battery

# Energy consumption
energy_consumption:
  # Base consumption rates in kWh/km
  base_rate_kwh_per_km: 1.55  # Higher consumption for regional operation
  consumption_range:
    min: 1.45
    max: 1.70
  
  # Adjustment factors
  load_adjustment_factor: 0.18  # 18% increase at full load vs empty
  temperature_adjustment:
    hot_weather: 0.06  # 6% increase in hot weather
    cold_weather: 0.15  # 15% increase in cold weather
  
  # Regenerative braking
  regenerative_braking_efficiency: 0.65  # 65% energy recovery efficiency
  regen_contribution_urban: 0.15  # 15% energy saving in mixed driving

# Charging specifications
charging:
  max_charging_power_kw: 350  # Higher power charging for faster turnaround
  charging_efficiency: 0.90  # 90% of electricity from grid becomes battery energy
  
  # Charging strategies and times
  charging_strategy: "overnight_depot"  # Default strategy
  strategies:
    overnight_depot:
      description: "Full charge overnight at depot"
      time_required_hours: 10  # More time for larger battery
      electricity_rate_type: "off_peak_tou"
    opportunity:
      description: "Fast charging during operation"
      time_required_hours: 1  # 1 hour for opportunity charging
      electricity_rate_type: "average_flat_rate"

# Performance specifications
performance:
  max_payload_tonnes: 24  # Lower than diesel equivalent due to battery weight
  range_km: 400  # Higher range for regional operations
  max_speed_kph: 90
  acceleration_0_50_kph_seconds: 22
  gradeability_percent: 12

# Maintenance
maintenance:
  cost_per_km: 0.09  # AUD per km
  annual_cost_at_reference_km: 7200  # At 80,000 km annually
  reference_km: 80000  # Higher annual distance for regional operations
  scheduled_maintenance_interval_km: 40000
  major_service_interval_km: 120000
  
  # Detailed costs
  detailed_costs:
    annual_fixed_min: 800
    annual_fixed_max: 1600
    per_km_variable: 0.06
    notes: "Higher distance but less stop-start than urban operations"

# Infrastructure parameters
infrastructure:
  charger_hardware_cost: 200000  # AUD - higher power chargers for regional fleet
  installation_cost: 75000  # AUD
  trucks_per_charger: 2.0  # Multiple trucks sharing chargers
  grid_upgrade_cost: 100000  # AUD - may need significant grid upgrades
  annual_maintenance_percent: 0.04  # 4% of hardware cost annually

# Available models reference
available_models:
  - manufacturer: "Volvo"
    model: "FH Electric"
    battery_kwh: 600
    range_km: 400
    max_charging_kw: 350
  - manufacturer: "Mercedes-Benz"
    model: "eActros 600"
    battery_kwh: 600
    range_km: 500
    max_charging_kw: 1000
    notes: "MCS charger capability"
  - manufacturer: "Tesla"
    model: "Semi"
    battery_kwh: 800
    range_km: 500
    max_charging_kw: 1000
    notes: "Proprietary charging network" 