# Diesel Truck Urban Delivery Configuration

# Basic vehicle information
vehicle_info:
  type: "diesel"
  category: "rigid"  # Urban delivery typically uses rigid trucks
  name: "Urban Diesel Delivery"
  description: "Conventional diesel rigid truck for urban delivery operations"

# Purchase and cost information
purchase:
  base_price_2025: 180000  # AUD
  annual_price_decrease_real: 0.0  # 0% real decrease per year
  notes: "Diesel truck prices stable or increasing slightly with emission standards"

# Engine specifications
engine:
  power_kw: 280  # Lower power for urban operations
  displacement_litres: 9.0
  emission_standard: "Euro VI"
  adblue_consumption_percent: 0.05  # 5% of diesel consumption
  engine_oil_capacity_litres: 30

# Fuel consumption
fuel_consumption:
  # Base consumption rates in L/100km
  base_rate_l_per_100km: 25.0  # Urban diesel consumption
  consumption_range:
    min: 23.0
    max: 30.0
  
  # Adjustment factors
  load_adjustment_factor: 0.20  # 20% increase at full load vs empty
  temperature_adjustment:
    hot_weather: 0.03  # 3% increase in hot weather
    cold_weather: 0.05  # 5% increase in cold weather
  
  # Idling
  idle_consumption_l_per_hour: 2.5
  estimated_idle_hours_per_1000km: 8.0  # Higher idle time in urban operations

# Refueling specifications
refueling:
  tank_capacity_litres: 400
  refueling_time_minutes: 15
  
  # Refueling strategies
  refueling_strategy: "depot"  # Default strategy
  strategies:
    depot:
      description: "Refuel at depot"
      frequency_days: 3
    public:
      description: "Refuel at public stations"
      frequency_days: 2
      price_premium_percent: 0.02  # 2% higher price at public stations

# Performance specifications
performance:
  max_payload_tonnes: 14  # Higher than BET due to lighter engine
  range_km: 1200  # Higher range with diesel
  max_speed_kph: 90
  acceleration_0_50_kph_seconds: 18
  gradeability_percent: 15

# Maintenance
maintenance:
  cost_per_km: 0.14  # AUD per km, higher than BET
  annual_cost_at_reference_km: 5600  # At 40,000 km annually
  reference_km: 40000  # Lower annual distance for urban operations
  scheduled_maintenance_interval_km: 20000  # More frequent than BET
  major_service_interval_km: 60000
  
  # Detailed costs
  detailed_costs:
    annual_fixed_min: 1000
    annual_fixed_max: 2000
    per_km_variable: 0.11
    notes: "Higher maintenance due to engine complexity, more frequent service intervals"

# Emissions
emissions:
  co2_g_per_km: 670  # Based on fuel consumption
  nox_g_per_km: 0.4
  pm_g_per_km: 0.01
  ghg_g_co2e_per_km: 700  # Including non-CO2 GHGs
  
  # Carbon cost
  carbon_cost_per_tonne_co2e: 50  # AUD per tonne CO2e
  carbon_cost_included: false  # Default setting

# Available models reference
available_models:
  - manufacturer: "Volvo"
    model: "FM 330"
    power_kw: 260
    displacement_litres: 8.0
    emission_standard: "Euro VI"
  - manufacturer: "Mercedes-Benz"
    model: "Actros 2536"
    power_kw: 290
    displacement_litres: 10.7
    emission_standard: "Euro VI"
  - manufacturer: "Isuzu"
    model: "FVR 165-300"
    power_kw: 221
    displacement_litres: 7.8
    emission_standard: "Euro V" 