# Battery Electric Truck (BET) Default Configuration

# Basic vehicle information
vehicle_info:
  type: "battery_electric"
  category: "articulated"
  name: "Default BET Articulated"

# Purchase and cost information
purchase:
  base_price_2025: 400000
  annual_price_decrease_real: 0.02

# Battery specifications
battery:
  capacity_kwh: 500
  usable_capacity_percentage: 0.90
  degradation_rate_annual: 0.02
  replacement_threshold: 0.70
  expected_lifecycle_years: 8
  replacement_cost_factor: 0.80

# Energy consumption
energy_consumption:
  base_rate_kwh_per_km: 1.45
  min_rate: 1.40
  max_rate: 1.50
  load_adjustment_factor: 0.15
  temperature_adjustment:
    hot_weather: 0.05
    cold_weather: 0.15
  regenerative_braking_efficiency: 0.65
  regen_contribution_urban: 0.20

# Charging specifications
charging:
  max_charging_power_kw: 350
  charging_efficiency: 0.90
  charging_strategy: "overnight_depot"
  strategies:
    overnight_depot:
      electricity_rate_type: "off_peak_tou"
    opportunity:
      electricity_rate_type: "average_tou"

# Performance specifications
performance:
  max_payload_tonnes: 26
  range_km: 350

# Maintenance
maintenance:
  cost_per_km: 0.08
  scheduled_maintenance_interval_km: 40000
  major_service_interval_km: 120000
  detailed_costs:
    annual_fixed_min: 700
    annual_fixed_max: 1500

# Infrastructure
infrastructure:
  charger_hardware_cost: 150000
  installation_cost: 50000
  maintenance_annual_percentage: 0.015
  trucks_per_charger: 1.0
  grid_upgrade_cost: 0

# Residual values
residual_values:
  year_5: [0.40, 0.50]
  year_10: [0.20, 0.30]
  year_15: [0.10, 0.15]